### ISSUE TITLE
500 Errors on Gogs - Update Org Delete Routine

### ISSUE THREAD

**Issue by eCyclops** [unfoldingWord-dev/gogs#136] opened 2017-01-18 20:12 UTC
When I log in to git.door43.org, the first page that comes up (location bar: https://git.door43.org) gives a 500 error. This is only after logging in. Similarly, I get a 500 error when clicking on the first three tabs: Dashboard, Issues, and Pull Requests. Explore, About Door43, and Help all take me to the relevant pages. I can also use "Your Profile" under the drop-down menu to get to what I think is similar to the Dashboard. This error is also reported by Max Murzamuratov. I suspect a global configuration or permissions issue.

## Notes

The best solution in the short term may be to write a pre-delete routine that cleans up the org connections (e.g. remove users from the org) before it deletes the organization.

**Comment by jag3773** [comment] 2017-01-30 18:22
The error I see in the log when John tries to load the page is:

> [...routers/user/home.go:47 getDashboardContextUser()] [E] GetOrganizations: user does not exist [uid: 4730, name: , keyid: 0]

**Comment by ethantkoenig** [comment] 2017-01-31 21:08
From poking around a bit, I looks like the user in question is marked as a member of a non-existent organization. When gogs loads the user's dashboard page, it tries to load all of the user's organizations, and fails. If I could get access to the underlying database, I could confirm whether this is in fact the case.

**Comment by ethantkoenig** [comment] 2017-02-05 19:43
It seems to me that the underlying problem is a lack of referential integrity in gitea. Unfornuately, gitea currently doesn't use foreign keys on columns that reference other tables, which can lead to problems like this. We should strive to eventually add foreign keys (probably through upstream, as they've also expressed some interest); it could prevent more problems like this.

**Comment by phillip-hopper** [comment] 2017-04-06 19:27
Not able to reproduce. There have been some changes to organizations and teams integrated from up-stream, perhaps they fixed this bug.

What I tried. I tested at each step and was not able to get any errors:
1. Added a new user, not on any team or organization.
2. Added a new organization.
3. Added the user to the team.
4. Deleted the team.
5. Opened the `team_user` table and added the user to an organization that does not exist.
6. Added the user to a team that doesn't exist in an organization that doesn't exist.

**Comment by eCyclops** [comment] 2017-04-06 19:30
Steps to reproduce:

1. login to https://git.door43.org
2. use username jdwood and appropriate password
3. get 500 error.

Subsequently, while logged in:

1. Click on Dashboard link.
2. Get 500 error.

John Wood
Cyclops Enterprises
jdwood@ecyclops.com <mailto:jdwood@ecyclops.com>


This message has been digitally signed using GPG. My key fingerprint is
51D8 C625 60E7 DC59 222C  7575 11EC 22E2 EB3F EAE0
and my key is available from pgp.mit.edu <http://pgp.mit.edu/> using EB3FEAE0 as the key id.

**Comment by phillip-hopper** [comment] 2017-04-06 19:40
@eCyclops This has not gone into production yet, sorry.

**Comment by eCyclops** [comment] 2017-04-06 19:42
Gotcha. Any idea when it will? It’s affecting more than just me, unfortunately.

John Wood
Cyclops Enterprises
jdwood@ecyclops.com <mailto:jdwood@ecyclops.com>


This message has been digitally signed using GPG. My key fingerprint is
51D8 C625 60E7 DC59 222C  7575 11EC 22E2 EB3F EAE0
and my key is available from pgp.mit.edu <http://pgp.mit.edu/> using EB3FEAE0 as the key id.

**Comment by richmahn** [comment] 2017-04-06 19:54
@eCyclops We can produce it in production, it is in development with all the new updates that we can't reproduce it. It will be in production in a week at the end of the current sprint

**Comment by eCyclops** [comment] 2017-04-06 19:56
Thanks. Looking forward to it!

John Wood
Cyclops Enterprises
jdwood@ecyclops.com <mailto:jdwood@ecyclops.com>


This message has been digitally signed using GPG. My key fingerprint is
51D8 C625 60E7 DC59 222C  7575 11EC 22E2 EB3F EAE0
and my key is available from pgp.mit.edu <http://pgp.mit.edu/> using EB3FEAE0 as the key id.

**Closed** 2017-04-12 19:49 UTC
Labels: bug, Can't Reproduce, Gogs

**Comment by mondele** [comment] 2017-05-16 17:03
Still waiting for resolution.

**Comment by andridzi** [comment] 2019-01-11 22:13
hi
I have the same issue now
gitea version is 1.6.3
