### ISSUE TITLE
Releases not appearing on repos

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/gogs#183] opened 2017-05-22 17:02 UTC
## Description
As a site admin, I want to be able to create a release for an end-user on one of their repos. What is currently happening is that if I do so, the releases page doesn't load.

Examples:

* https://git.door43.org/parfait-ayanou/pem-x-gipendegu_jas_text_reg/releases
* https://git.door43.org/kwaduo/gaj-x-ymnk_obs_text_obs/releases

## Screenshots
Screenshot wouldn't be useful. The page doesn't load. (Not even enough html to show page source.)

**Comment by ethantkoenig** [comment] 2017-06-02 01:46
I'm unable to reproduce this locally. Could someone provide a log?

**Comment by ethantkoenig** [comment] 2017-06-02 01:54
Or better yet, could someone teach me how/where to view production logs?

**Comment by mondele** [comment] 2017-06-02 02:02
I'm not sure what kind of log I could create. Here's what's displayed when I load the page in Opera in Centos 7: This page isn't working - git.door43.org is currently unable to handle this request.

This is the result for both links above. In Safari I just get a blank page. Brave browser indicates a 500 error.

**Comment by ethantkoenig** [comment] 2017-06-02 02:14
@mondele No, I mean the logs that gitea/gogs/DCS automatically generates, not any sort of log you would create manually.

**Comment by mondele** [comment] 2017-06-02 02:27
Okay, that I will need to leave to your team. :-)

**Comment by richmahn** [comment] 2017-06-02 08:26
@ethantkoenig If @jag3773 gives you access to the aws server you can see them. Here's what I see when tailing the log and going to the release page:

/usr/local/go/src/runtime/panic.go:489 (0x42c42f)
/usr/local/go/src/runtime/panic.go:35 (0x42b11e)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/code.gitea.io/git/repo_tag.go:136 (0x7ea426)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/code.gitea.io/git/repo_tag.go:164 (0x7ea716)
/tmp/go-muQC/src/code.gitea.io/gitea/routers/repo/release.go:70 (0xe3f8f4)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x4592f8)
/usr/local/go/src/reflect/value.go:434 (0x4bba9f)
/usr/local/go/src/reflect/value.go:302 (0x4bb064)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x8566bf)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x85608a)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x883382)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x8832a6)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:186 (0x8da9e0)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x4592f8)
/usr/local/go/src/reflect/value.go:434 (0x4bba9f)
/usr/local/go/src/reflect/value.go:302 (0x4bb064)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x8566bf)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x85608a)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x883382)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 (0x8832a6)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x89640b)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x4592f8)
/usr/local/go/src/reflect/value.go:434 (0x4bba9f)
/usr/local/go/src/reflect/value.go:302 (0x4bb064)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x8566bf)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x85608a)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 (0x883382)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:184 (0x8976d9)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:288 (0x88f7bd)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x8877ec)
/tmp/go-muQC/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xab268b)
/usr/local/go/src/net/http/server.go:1942 (0x6d3894)
/usr/local/go/src/net/http/server.go:2568 (0x6d6152)
/usr/local/go/src/net/http/server.go:1825 (0x6d2402)
/usr/local/go/src/runtime/asm_amd64.s:2197 (0x45bab1)

**Comment by richmahn** [comment] 2017-06-02 08:51
Also, from the release table for https://git.door43.org/parfait-ayanou/pem-x-gipendegu_jas_text_reg/releases:

```
mysql> select * from `release` where repo_id = 10321;
+-----+---------+--------------+------------+----------------+--------+-----------------+------------------------------------------+-------------+----------------------------------------------------------------------------------------------------+----------+---------------+--------------+
| id  | repo_id | publisher_id | tag_name   | lower_tag_name | target | title           | sha1                                     | num_commits | note
                                                                            | is_draft | is_prerelease | created_unix |
+-----+---------+--------------+------------+----------------+--------+-----------------+------------------------------------------+-------------+----------------------------------------------------------------------------------------------------+----------+---------------+--------------+
| 135 |   10321 |         4254 | Level1     | level1         | master | Level 1         | a6e07e9bfdcb4a5ad3394a3532797836bcb492a1 |         194 | Kinshasa MAST avril 2017
Source text: ULB-fr https://git.door43.org/parfait-ayanou/fr_mat_jas_ulb |        0 |             0 |   1495459642 |
| 136 |   10321 |         4254 | Level1-bis | level1-bis     | master | Level 1 Release | a6e07e9bfdcb4a5ad3394a3532797836bcb492a1 |         194 | Kinshasa MAST avril 2017
source: ULB français (en voie de vérification au niveau 3)               |        0 |             0 |   1495460103 |
+-----+---------+--------------+------------+----------------+--------+-----------------+------------------------------------------+-------------+----------------------------------------------------------------------------------------------------+----------+---------------+--------------+```

**Comment by richmahn** [comment] 2017-06-02 09:28
Lastly, looking at line 154 of repo_tag.go in code.gitea.io/git, I did my own git command line it does to get the tags:

```
[root@ip-172-31-38-86 pem-x-gipendegu_jas_text_reg.git]# git log --tags --simplify-by-decoration --pretty=format:"%ci %d %H %cn<%ce> %s"
2017-05-09 13:21:21 +0100  (HEAD -> master, tag: Level1-bis, tag: Level1) a6e07e9bfdcb4a5ad3394a3532797836bcb492a1 parfait-ayanou<you@example.com> Tue May 09 2017 13:21:21 GMT+0100 (W. Central Africa Standard Time)
2017-05-04 15:04:21 +0100  b4240b6b4ff06277e0e76fbb792a6ab15eb7b91d root<root@localhost> auto save
```

I'm guessing this second line is not able to be parsed right? No `tag:` in it for line 121 in repo_tag.go. Other than that, can't figure out what is going on.

**Comment by ethantkoenig** [comment] 2017-06-02 14:39
Looks like it's a bug in `code.gitea.io/git/repo_tag.go`. I'll work on a fix.

**Comment by mondele** [comment] 2017-06-02 14:57
Is there anything we could change in creating the Release that would avoid this? (Thanks for working on a fix.)

**Comment by ethantkoenig** [comment] 2017-06-02 15:27
See https://github.com/go-gitea/git/pull/58

**Comment by richmahn** [comment] 2017-06-08 23:19
@ethantkoenig Yeah, I see this has been fixed in upstream and you even have done some work with releases, but how can we get this fixed in the next release? I tested cherry picking some of these commits, but since other files are changed in other commits, it got pretty hairy. Can you see if we can get May/June commits to fix releases into our fork? https://github.com/go-gitea/gitea/commits/0cf89a83c111fe49a8be48c46873182479260d8e/vendor/code.gitea.io/git

**Comment by ethantkoenig** [comment] 2017-06-08 23:22
@richmahn Probably easiest just to merge all commits from upstream, I'll take a look

**Comment by richmahn** [comment] 2017-06-10 01:44
@ethantkoenig Yeah, if you could do that, that would be great. Probably would be easiest and best.

**Comment by richmahn** [comment] 2017-06-10 01:44
Ah, I guess you did. Thanks. So to note, this has been fixed from changes upstream

**Comment by richmahn** [comment] 2017-06-14 15:09
@mondele This issue is now fixed on production: 

https://git.door43.org/parfait-ayanou/pem-x-gipendegu_jas_text_reg/releases
https://git.door43.org/kwaduo/gaj-x-ymnk_obs_text_obs/releases

**Closed** 2017-06-15 14:22 UTC
Labels: bug, Gogs
