### ISSUE TITLE
About DCS is throwing a error 404

### ISSUE THREAD

**Issue by sea-liesch** [unfoldingWord-dev/gogs#205] opened 2017-06-26 15:41 UTC
https://git.door43.org/Door43/pages/wiki/Welcome-to-Door43-Content-Service%21   Gives the 404 error page not found.
~Chuck

**Comment by jag3773** [comment] 2017-06-26 16:12
This is a duplicate of #198 and will be fixed in the next release.

**Closed** 2017-06-29 14:33 UTC
